#ifndef __MSCHANNEL__INC__HH__
#define __MSCHANNEL__INC__HH__

#define MS_SOURCE_CHANNEL_ID	9013
#define MS_OUTPUT_CHANNEL_ID	9014

#define MS_FILTER_GET_SOURCE_CAHNNEL				MS_FILTER_METHOD(MS_SOURCE_CHANNEL_ID,0,void*)
#define MS_FILTER_SET_SOURCE_CAHNNEL_MSG			MS_FILTER_METHOD(MS_SOURCE_CHANNEL_ID,1,void*)
#define MS_FILTER_GET_OUTPUT_CAHNNEL				MS_FILTER_METHOD(MS_OUTPUT_CHANNEL_ID,0,void*)


void mschannel_init(void);

#endif
